services:
  # ─────────────────────────────────────────
  #  ADGUARD – STOP PUB
  # ─────────────────────────────────────────
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    volumes:
      - ${CONFIG}/adguard/work:/opt/adguardhome/work
      - ${CONFIG}/adguard/conf:/opt/adguardhome/conf
    networks:
      - proxy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3002:3000/tcp"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard-lan.rule=Host(`adguard.lan`)
      - traefik.http.routers.adguard-lan.entrypoints=websecure
      - traefik.http.routers.adguard-lan.tls=true
      - traefik.http.services.adguard-lan.loadbalancer.server.port=3000
networks:
  proxy:
    external: true
